"""
database.py
This module handles all MongoDB database operations for the image processing platform.
It manages connections to local MongoDB database and performs CRUD operations.
"""

from pymongo import MongoClient
from pymongo.errors import ConnectionFailure
from bson.objectid import ObjectId
import os
from datetime import datetime

# Database configuration
MONGODB_URI = os.environ.get('MONGODB_URI', 'mongodb://localhost:27017/')
DB_NAME = os.environ.get('DB_NAME', 'image_storage')

# Global client instance
_client = None
_db = None


def get_database():
    """
    Establishes and returns a connection to the MongoDB database.
    
    Returns:
        database: MongoDB database object
        
    Raises:
        Exception: If connection fails
    """
    global _client, _db
    
    try:
        if _client is None:
            _client = MongoClient(MONGODB_URI, serverSelectionTimeoutMS=5000)
            # Test the connection
            _client.admin.command('ping')
            _db = _client[DB_NAME]
            print("✓ Database connection established successfully")
        
        return _db
    except ConnectionFailure as e:
        print(f"✗ Database connection failed: {str(e)}")
        raise
    except Exception as e:
        print(f"✗ Unexpected error connecting to database: {str(e)}")
        raise


def create_images_collection():
    """
    Creates the 'images' collection in the database if it doesn't exist.
    
    Document structure:
        - _id: Primary key (auto-generated by MongoDB)
        - file_name: Name of the uploaded image
        - original_size: Size of original image in bytes
        - processed_size: Size of processed image in bytes
        - upload_time: Timestamp of upload
        - image_url: S3 URL of the processed image
    """
    try:
        db = get_database()
        
        # Create collection if it doesn't exist
        if 'images' not in db.list_collection_names():
            db.create_collection('images')
            # Create indexes for better query performance
            db.images.create_index([('upload_time', -1)])
            db.images.create_index([('file_name', 1)])
            print("✓ Images collection created successfully")
        else:
            print("✓ Images collection already exists")
        
    except Exception as e:
        print(f"✗ Error creating collection: {str(e)}")
        raise


def insert_image_metadata(file_name, original_size, processed_size, image_url):
    """
    Inserts image metadata into the database.
    
    Args:
        file_name (str): Name of the image file
        original_size (int): Size of original image in bytes
        processed_size (int): Size of processed image in bytes
        image_url (str): S3 URL of the processed image
        
    Returns:
        str: ID of the inserted record
        
    Raises:
        Exception: If insertion fails
    """
    try:
        db = get_database()
        
        # Current timestamp
        upload_time = datetime.now()
        
        # Document to insert
        image_doc = {
            'file_name': file_name,
            'original_size': original_size,
            'processed_size': processed_size,
            'upload_time': upload_time,
            'image_url': image_url
        }
        
        # Insert the document
        result = db.images.insert_one(image_doc)
        image_id = str(result.inserted_id)
        
        print(f"✓ Image metadata inserted successfully (ID: {image_id})")
        return image_id
        
    except Exception as e:
        print(f"✗ Error inserting image metadata: {str(e)}")
        raise


def get_image_metadata(image_id):
    """
    Retrieves image metadata from the database by ID.
    
    Args:
        image_id (str): ID of the image record (MongoDB ObjectId as string)
        
    Returns:
        dict: Image metadata or None if not found
    """
    try:
        db = get_database()
        
        # Query to retrieve image metadata
        result = db.images.find_one({'_id': ObjectId(image_id)})
        
        # Convert ObjectId to string for JSON serialization
        if result:
            result['id'] = str(result['_id'])
            del result['_id']
        
        return result
        
    except Exception as e:
        print(f"✗ Error retrieving image metadata: {str(e)}")
        return None


def get_all_images():
    """
    Retrieves all image records from the database.
    
    Returns:
        list: List of all image metadata dictionaries
    """
    try:
        db = get_database()
        
        # Query to retrieve all images, sorted by upload_time descending
        results = list(db.images.find().sort('upload_time', -1))
        
        # Convert ObjectId to string for JSON serialization
        for result in results:
            result['id'] = str(result['_id'])
            del result['_id']
        
        return results
        
    except Exception as e:
        print(f"✗ Error retrieving images: {str(e)}")
        return []


# Initialize the database collection when this module is imported
if __name__ == "__main__":
    # This will create the collection if run directly
    print("Initializing database...")
    create_images_collection()
    print("✓ Database initialization complete!")
